### ISSUE TITLE
Library does not handle orientation changes correctly when action mode is on

### ISSUE THREAD

**Issue by lakeba** [ManuelPeinado/MultiChoiceAdapter#1]
This is a very good Job, I have also sent to you a crash report.
Could you implement the restoring of ActionMode when items are selected and Rotation happened ?

**Comment by ManuelPeinado** [comment]
Thanks a lot for the crash report, I've just published v1.0.7 which (hopefully) fixes the bug

**Comment by lakeba** [comment]
In the 1.0.7 are you managing the action mode on rotation?
Il giorno 18/apr/2013 22:00, "ManuelPeinado" notifications@github.com ha
scritto:

**Comment by ManuelPeinado** [comment]
Yes, I did it in previous versions too but there was a bug which prevented things from working as they should. I've just uploaded the new version of the demo app to Google Play, so it should be available in a couple of hours. In the meantime you can compile it yourself, it's already on github.
