### ISSUE TITLE
How to handle separator views

### ISSUE THREAD

**Issue by qmrk** [ManuelPeinado/MultiChoiceAdapter#10]
I have a listview which contains different types of separator views. I can't seem to figure out, how to disable, that these items get added to the selection when long clicked on.

Also, some of the separator items are not supposed to be added to the multichoice selection, but still should be clickable, to allow a view change. How to go about this?

Any help is appreciated! Thanks.
Rob

**Comment by ManuelPeinado** [comment]
That's definitely not supported by the library. I'll see if I can think of
a good way to add it without complicating the API too much. In the mean
time, I recommend you just fork the lib and adapt it to your needs, the
code is pretty straightforward.

**Comment by qmrk** [comment]
Ok, thanks for the quick reply! That's what i figured... Just wanted to make sure, before I start messing with your code ;-)

Thanks for this nice library, btw!

**Comment by ManuelPeinado** [comment]
I've added support for this in v2.2.4. Check the "non-checkable items" sample to see what you should do, it's basically a matter of overriding the new isItemCheckable() method in your adapter.
