### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by sakulisko** [ManuelPeinado/MultiChoiceAdapter#15]
Please can you add functionality for translating title in contextual action bar?

**Comment by ManuelPeinado** [comment]
Just add a plurals.xml file to the appropriate res/values folder of your app (for instance, res/values_es for Spanish). 

Then copy the content of mca__plurals to this file, changing the values of the strings as needed. 

For Spanish you would have something like this:

```
<plurals name="selected_items">
    <item quantity="one">1 item seleccionado</item>
    <item quantity="other">%d items seleccionados</item>
</plurals>
```

**Comment by sakulisko** [comment]
It's working. Thanks.
