### ISSUE TITLE
How to handle header and footer views that are uncheckable?

### ISSUE THREAD

**Issue by derekbrameyer** [ManuelPeinado/MultiChoiceAdapter#4]
I tried overriding setItemChecked() as follows:

```
@Override
public void setItemChecked(int position, boolean checked) {
    // Account for 1 header view
    super.setItemChecked(position - 1, checked);
}
```

This didn't seem to make a difference. Any help would be appreciated!

**Comment by ManuelPeinado** [comment]
Fixed in v2.1.1. Source code already in github, artifacts should be in maven central in a couple hours.

Good catch, Derek, thanks a lot. BTW, if you release an app using MultiChoiceAdapter please let me know and I will add a link to the README
