### ISSUE TITLE
Use AlphabetIndexer with MultiChoiceBaseAdapter

### ISSUE THREAD

**Issue by lakeba** [ManuelPeinado/MultiChoiceAdapter#9]
Any chance to use the AlphabetIndexer with MultiChoiceBaseAdapter ?

**Comment by ManuelPeinado** [comment]
As far as I know AlphabetIndex must be used with a cursor, so you'll have to use MultiChoiceSimpleCursorAdapter. 

I've written a sample that demonstrates that this is in fact pretty easy:

https://github.com/ManuelPeinado/MultiChoiceAdapter/tree/master/sample/src/com/manuelpeinado/multichoiceadapter/demo/alphabetindexersample

**Comment by lakeba** [comment]
I have implemented it also for MultiChoiceBaseAdapter, do you want me to merge it?

**Comment by ManuelPeinado** [comment]
There's something I don't understand. If you don't have a cursor, what do you pass AlphabetIndexer#setCursor? And if you do have a cursor, why don't you use a MultiChoiceSimpleCursorAdapter?

**Comment by lakeba** [comment]
I have just implemented SectionIndexer

Attached my class

It work a charm.
